### ISSUE TITLE
Desain Logo Bengkelin

### ISSUE THREAD

**Issue by xamppsul** [syamsulapp/begkelin#1]

**Comment by kamilanawa** [comment]
![logo bengkelin](https://github.com/syamsulapp/begkelin/assets/125983493/af1cef74-6c31-4821-a7ef-e6a629853dac)

**Comment by kamilanawa** [comment]
![logo bengkelin new](https://github.com/syamsulapp/begkelin/assets/125983493/12eca2a3-77b8-4937-8eda-4cfd4e6c5aa2)

**Comment by kamilanawa** [comment]
logonya kayak kekecilan gasi , bte aku udah terapin di web nya tapi pas aku terapin mau aku push gabisa 
![Uploading WhatsApp Image 2023-11-06 at 18.06.44.jpeg…]()

**Comment by kamilanawa** [comment]
![Uploading WhatsApp Image 2023-11-06 at 18.06.44.jpeg…]()

**Comment by kamilanawa** [comment]
@syamsulapp cek
