### ISSUE TITLE
task/improve-authenication

### ISSUE THREAD

**Issue by kamilanawa** [syamsulapp/begkelin#12]
Logo di  bagian login kurang ke bawah 
belum ada flash data success ketika after register success redirect to login
fix logic login between user and pemilik bengkel use same email
fix logic register between user and pemilik bengkel use same email
errors authentication(login) put on pop up

**Comment by xamppsul** [comment]
@kamilanawa jangan lupa di review lagi yah

**Comment by deepDeployCode** [comment]
@kamilanawa gw udah push di branch yah jangan lupa di pull terus di testing/review

**Comment by deepDeployCode** [comment]
> Logo di bagian login kurang ke bawah belum ada flash data success ketika after register success redirect to login

@kamilanawa terus kalo ada bug langsung berkabar di issue ini ajah terimakasih.
